# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherSalad' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherSalad

	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'SnapKit'
  target 'WeatherSaladTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeatherSaladUITests' do
    # Pods for testing
  end

end
